### ISSUE TITLE
Not able to swap

### ISSUE THREAD

**Issue by stoneycreeky** [0xmef/sanctum_swap#1]
Hi,

The 1 - Register sanctum accounts and 3 - Check EXP count works fine for me. But 2 - Swap SOL to INF always hang in there. I have left enough balance for SOL and also changed to other RPC as well.

Anyway I can make a successful SWAP to INF? thank you!

**Comment by 0xmef** [comment]
Hi,
show ur tx hashes or drop wallet address

maybe u try to swap more, than have. You can try to decrease token range in config and test again
Increase max_retries and wait if tx is not confirmed > will try again to swap max_retries times

also u can dm me to telegram (@three_hundred300)
